#!/bin/bash
# SPDX-License-Identifier: EUPL-1.2
#
# This file is part of util-linux
#
# Copyright (C) 2024 Thijs Raymakers
# Licensed under the EUPL v1.2

TS_TOPDIR="${0%/*}/../.."
TS_DESC="coresched"

. "$TS_TOPDIR"/functions.sh
ts_init "$*"

ts_check_test_command "$TS_CMD_CORESCHED"

# Because we have no control over the values of the PIDs and the core scheduling cookies,
# we have to dynamically detect them and replace them with some placeholders so it can match
# the expected output
ts_init_subtest "get-own-pid-no-cookie"
$TS_CMD_CORESCHED -p $$ 3>&2 2>&1 1>&3 | sed "s/$$/OWN_PID/g" >> "$TS_OUTPUT"
ts_finalize_subtest

ts_init_subtest "set-cookie-own-pid"
CORESCHED_OUTPUT=`$TS_CMD_CORESCHED -v -n -p $$ 3>&2 2>&1 1>&3 | sed "s/$$/OWN_PID/g"`
CORESCHED_COOKIE=`echo $CORESCHED_OUTPUT | sed 's/^.*\(0x.*$\)/\1/g'`
CORESCHED_OUTPUT=`echo $CORESCHED_OUTPUT | sed "s/$CORESCHED_COOKIE/COOKIE/g"`
echo $CORESCHED_OUTPUT >> "$TS_OUTPUT"
ts_finalize_subtest

ts_init_subtest "get-own-pid-with-cookie"
$TS_CMD_CORESCHED -p $$ | sed "s/$$/OWN_PID/g" | sed "s/$CORESCHED_COOKIE/COOKIE/g" >> "$TS_OUTPUT"
ts_finalize_subtest

ts_init_subtest "spawn-child-with-new-cookie"
$TS_CMD_CORESCHED -n -- bash -c "$TS_CMD_CORESCHED -p \$\$" \
  | sed 's/^.*\(0x.*$\)/\1/g' \
  | sed "s/$CORESCHED_COOKIE/SAME_COOKIE/g" \
  | sed "s/0x.*$/DIFFERENT_COOKIE/g" >> "$TS_OUTPUT"
ts_finalize_subtest

ts_init_subtest "change-cookie-of-parent"
$TS_CMD_CORESCHED -n -- bash -c "$TS_CMD_CORESCHED -c -p \$\$ -d $$"
$TS_CMD_CORESCHED -p $$ \
  | sed "s/$$/OWN_PID/g" \
  | sed "s/$CORESCHED_COOKIE/COOKIE/g" \
  | sed "s/0x.*$/DIFFERENT_COOKIE/g" >> "$TS_OUTPUT"
ts_finalize_subtest

ts_finalize
