//po4a: entry man manual
////
coresched(1) manpage
////
= coresched(1)
:doctype: manpage
:man manual: User Commands
:man source: util-linux {release-version}
:page-layout: base
:command: coresched
:colon: :
:copyright: ©

== NAME

coresched - manage core scheduling cookies for tasks

== SYNOPSIS

*{command}* [options] *-p* _pid_

*{command}* [options] \-- _command_ [_argument_...]

== DESCRIPTION
The *{command}* command is used to retrieve or modify the core scheduling cookies of a running process given its _pid_, or to spawn a new _command_ with core scheduling cookies.

Core scheduling allows you to define groups of tasks that are allowed to share a physical core.
This is done by assigning a cookie to each task.
Only tasks have the same cookie are allowed to be scheduled on the same physical core.

It is possible to either assign a new random cookie to a task, or copy a cookie from another task. It is not possible to choose the value of the cookie.

== FUNCTIONS
*-n*, *--new*::
Assign a new cookie to an existing PID or to execute _command_ with a new cookie.

*-c*, *--copy*::
Copy the cookie from an existing PID to another PID, or execute _command_ with that copied cookie.

If no function is specified, it will retrieve and print the cookie of a task.

== OPTIONS
*-p*, *--pid* _PID_::
Operate on an existing PID and do not launch a new task.

*-d*, *--dest* _PID_::
When using *--copy*, specify a destination PID where you want to copy the cookie to.

*-t*, *--type* _TYPE_::
The type of the PID whose cookie will be modified. This can be one of three values:
- *pid*, or process ID
- *tgid*, or thread group ID (default value)
- *pgid*, or process group ID

*-v*, *--verbose*::
Show extra information when modifying cookies of tasks.

*-h*, *--help*::
Display help text and exit.

*-V*, *--version*::
Print version and exit.

== EXAMPLES
Get the core scheduling cookie of a task with PID _123_{colon}::
*{command} -p* _123_

Give a task with PID _123_ a new core scheduling cookie{colon}::
*{command} --new -p* _123_

Spawn a new task with a new core scheduling cookie{colon}::
*{command} --new* \-- _command_ [_argument_...]

Copy the cookie from a task with pid _123_ to another task with pid _456_{colon}::
*{command} --copy -p* _123_ *-d* _456_

Copy the cookie from a task with pid _123_ to a new task _command_{colon}::
*{command} --copy -p* _123_ \-- _command_ [_argument_...]

Copy the cookie from a task with pid _123_ to the process group ID _456_{colon}::
*{command} --copy -p* _123_ *-t* pgid *-d* _456_

== PERMISSIONS
When retrieving or modifying the core scheduling cookie of a process, you need to have *PTRACE_MODE_READ_REALCREDS* ptrace access to that process.
See the section "Ptrace access mode checking" in *ptrace*(2) for more information.

== RETURN VALUE
On success, *{command}* returns 0.
If *{command}* fails, it will print an error and return 1.
If core scheduling is not supported with your kernel (e.g. because *CONFIG_SCHED_CORE*=n), then it will return 95 (*ENOTSUP*).

== AUTHORS
mailto:thijs@raymakers.nl[Thijs Raymakers],
mailto:pauld@redhat.com[Phil Auld]

== COPYRIGHT

Copyright {copyright} 2024 Thijs Raymakers and Phil Auld. This is free software licensed under the EUPL.

== SEE ALSO
*chrt*(1),
*nice*(1),
*renice*(1),
*taskset*(1),
*ptrace*(2),
*sched*(7)

The Linux kernel source files _Documentation/admin-guide/hw-vuln/core-scheduling.rst_

include::man-common/bugreports.adoc[]

include::man-common/footer.adoc[]

ifdef::translation[]
include::man-common/translation.adoc[]
endif::[]
